from enum import Enum
from pathlib import Path

from mir_commander.api.data_structures.atomic_coordinates import AtomicCoordinates
from mir_commander.api.data_structures.molecule import Molecule
from mir_commander.api.file_importer import ImportFileError, InvalidFormatError
from mir_commander.api.project_node_schema import ActionType
from mir_commander.api.project_node_schema import ProjectNodeSchemaV1 as Node
from mir_commander.core.chemistry import symbol_to_atomic_number

from .utils import load_lines


class MDLMolV2000ParserState(Enum):
    INIT = 0
    CONTROL = 1
    ATOM = 2
    BOND = 3


def _validate(path: Path):
    lines = load_lines(path, 4)
    if " V2000" not in lines[3]:
        raise InvalidFormatError()


def read(path: Path, logs: list[str]) -> Node:
    """
    Import data from MDL Mol V2000 file, build and populate a respective tree of items.
    Also return a list of flagged items.
    Additionally return a list of messages, which can be printed later.
    """
    _validate(path)

    logs.append("MDL Molfile V2000.")

    result = Node(name=path.name, data=Molecule(), type="builtin.molecule")

    title = ""

    state = MDLMolV2000ParserState.INIT
    at_coord_item = None
    with path.open("r") as input_file:
        for line_number, line in enumerate(input_file):
            if state == MDLMolV2000ParserState.INIT:
                if len(title) == 0:
                    title = line.strip()
                if line_number == 2:
                    state = MDLMolV2000ParserState.CONTROL
            elif state == MDLMolV2000ParserState.CONTROL:
                line_items = line.strip().split()

                try:
                    num_atoms = int(line_items[0])
                except ValueError:
                    raise ImportFileError(f"Invalid control line {line_number + 1}, expected number of atoms.")

                try:
                    num_bonds = int(line_items[1])
                except ValueError:
                    raise ImportFileError(f"Invalid control line {line_number + 1}, expected number of bonds.")

                if num_atoms <= 0:
                    raise ImportFileError(f"Invalid number of atoms {num_atoms} defined in line {line_number + 1}.")

                if num_bonds < 0:
                    raise ImportFileError(f"Invalid number of bonds {num_atoms} defined in line {line_number + 1}.")

                num_read_at_cards = 0
                atom_atomic_num = []
                atom_coord_x = []
                atom_coord_y = []
                atom_coord_z = []
                state = MDLMolV2000ParserState.ATOM
            elif state == MDLMolV2000ParserState.ATOM:
                line_items = line.strip().split()

                try:
                    coord_x = float(line_items[0])
                    coord_y = float(line_items[1])
                    coord_z = float(line_items[2])
                except ValueError:
                    # Something is wrong with format
                    raise ImportFileError(f"Invalid atom coordinate value(s) at line {line_number + 1}.")

                try:
                    # Convert here atomic symbol to atomic number
                    if line_items[3] == "X":
                        atomic_num = -1
                    elif line_items[3] == "Q":
                        atomic_num = -2
                    else:
                        atomic_num = symbol_to_atomic_number(line_items[3])
                except ValueError:
                    raise ImportFileError(f"Invalid atom symbol at line {line_number + 1}.")

                num_read_at_cards += 1
                atom_atomic_num.append(atomic_num)
                atom_coord_x.append(coord_x)
                atom_coord_y.append(coord_y)
                atom_coord_z.append(coord_z)

                if num_read_at_cards == num_atoms:
                    if not title:
                        title = path.name

                    at_coord_item = Node(
                        name=title,
                        type="builtin.atomic_coordinates",
                        data=AtomicCoordinates(
                            atomic_num=atom_atomic_num, x=atom_coord_x, y=atom_coord_y, z=atom_coord_z
                        ),
                    )
                    result.nodes.append(at_coord_item)

                    state = MDLMolV2000ParserState.BOND
            elif state == MDLMolV2000ParserState.BOND:
                # TODO: read here explicit bonds, but the viewer must be reimplemented,
                # so that the bonds are not necessarily autogenerated.
                break

    # Mark the last imported coordinates for auto-opening
    if result.nodes:
        result.nodes[-1].actions.append(ActionType.OPEN)

    return result
