import logging
from enum import Enum
from pathlib import Path

import numpy as np
from periodictable import elements

from mir_commander import errors
from mir_commander.data_structures.molecule import Molecule, AtomicCoordinates
from mir_commander.ui.utils import item

from .utils import ItemParametrized

logger = logging.getLogger(__name__)


class MDLMolV2000ParserState(Enum):
    INIT = 0
    CONTROL = 1
    ATOM = 2
    BOND = 3


def load_mdlmol2000(path: Path) -> tuple[item.Item, list[dict], list[str]]:
    """
    Import data from MDL Mol V2000 file, build and populate a respective tree of items.
    Also return a list of flagged items.
    Additionally return a list of messages, which can be printed later.
    """
    flagged_items: list[dict] = []
    messages: list[str] = []

    messages.append("MDL Molfile V2000.")

    moldata = Molecule()
    molitem = item.Molecule(path.parts[1], moldata)
    molitem.file_path = path

    title = ""

    flagged_items.append({"itempar": ItemParametrized(molitem, {}), "expand": True})

    state = MDLMolV2000ParserState.INIT
    at_coord_item = None
    with path.open("r") as input_file:
        for line_number, line in enumerate(input_file):
            if state == MDLMolV2000ParserState.INIT:
                if len(title) == 0:
                    title = line.strip()
                if line_number == 2:
                    state = MDLMolV2000ParserState.CONTROL
            elif state == MDLMolV2000ParserState.CONTROL:
                line_items = line.strip().split()

                try:
                    num_atoms = int(line_items[0])
                except ValueError:
                    raise errors.LoadFileError(f"Invalid control line {line_number + 1}, expected number of atoms.")

                try:
                    num_bonds = int(line_items[1])
                except ValueError:
                    raise errors.LoadFileError(f"Invalid control line {line_number + 1}, expected number of bonds.")

                if num_atoms <= 0:
                    raise ValueError(f"Invalid number of atoms {num_atoms} defined in line {line_number+1}.")

                if num_bonds < 0:
                    raise ValueError(f"Invalid number of bonds {num_atoms} defined in line {line_number+1}.")

                num_read_at_cards = 0
                atom_atomic_num = []
                atom_coord_x = []
                atom_coord_y = []
                atom_coord_z = []
                state = MDLMolV2000ParserState.ATOM
            elif state == MDLMolV2000ParserState.ATOM:
                line_items = line.strip().split()

                try:
                    coord_x = float(line_items[0])
                    coord_y = float(line_items[1])
                    coord_z = float(line_items[2])
                except ValueError:
                    # Something is wrong with format
                    logger.info(f"Invalid atom coordinate value(s) at line {line_number + 1}.")
                    raise

                try:
                    # Convert here atomic symbol to atomic number
                    if line_items[3] == "X":
                        atomic_num = -1
                    elif line_items[3] == "Q":
                        atomic_num = -2
                    else:
                        atomic_num = elements.symbol(line_items[3]).number
                except ValueError:
                    logger.info(f"Invalid atom symbol at line {line_number + 1}.")
                    raise

                num_read_at_cards += 1
                atom_atomic_num.append(atomic_num)
                atom_coord_x.append(coord_x)
                atom_coord_y.append(coord_y)
                atom_coord_z.append(coord_z)

                if num_read_at_cards == num_atoms:
                    # Add the set of Cartesian coordinates directly to the molecule
                    at_coord_data = AtomicCoordinates(
                        np.array(atom_atomic_num, dtype="int16"),
                        np.array(atom_coord_x, dtype="float64"),
                        np.array(atom_coord_y, dtype="float64"),
                        np.array(atom_coord_z, dtype="float64"),
                    )
                    if len(title) == 0:
                        title = path.name
                    at_coord_item = item.AtomicCoordinates(title, at_coord_data)
                    molitem.appendRow(at_coord_item)

                    state = MDLMolV2000ParserState.BOND
            elif state == MDLMolV2000ParserState.BOND:
                # TODO: read here explicit bonds, but the viewer must be reimplemented,
                # so that the bonds are not necessarily autogenerated.
                break

    # Autoview last set of coordinates
    if at_coord_item:
        flagged_items.append({"itempar": ItemParametrized(at_coord_item, {"maximize": True}), "view": True})

    return molitem, flagged_items, messages
