import logging
from enum import Enum
from pathlib import Path

from periodictable import elements

from ..errors import LoadFileError
from ..models import AtomicCoordinates, Item, Molecule
from .consts import babushka_priehala

logger = logging.getLogger("Parsers.MDLMol2000Parser")

class MDLMolV2000ParserState(Enum):
    INIT = 0
    CONTROL = 1
    ATOM = 2
    BOND = 3


def is_mdlmol2000(lines: list[str]) -> bool:
    return " V2000" in lines[3]


def load_mdlmol2000(path: Path, logs: list) -> Item:
    """
    Import data from MDL Mol V2000 file, build and populate a respective tree of items.
    Also return a list of flagged items.
    Additionally return a list of messages, which can be printed later.
    """
    logger.info("Loading MDLMol2000 file ...")

    logs.append("MDL Molfile V2000.")

    result = Item(name=path.name, data=Molecule(), metadata={"type": "mdlmol2000"})

    title = ""

    state = MDLMolV2000ParserState.INIT
    at_coord_item = None
    with path.open("r") as input_file:
        for line_number, line in enumerate(input_file):
            if state == MDLMolV2000ParserState.INIT:
                if len(title) == 0:
                    title = line.strip()
                if line_number == 2:
                    state = MDLMolV2000ParserState.CONTROL
            elif state == MDLMolV2000ParserState.CONTROL:
                line_items = line.strip().split()

                try:
                    num_atoms = int(line_items[0])
                except ValueError:
                    raise LoadFileError(f"Invalid control line {line_number + 1}, expected number of atoms.")

                try:
                    num_bonds = int(line_items[1])
                except ValueError:
                    raise LoadFileError(f"Invalid control line {line_number + 1}, expected number of bonds.")

                if num_atoms <= 0:
                    raise LoadFileError(f"Invalid number of atoms {num_atoms} defined in line {line_number + 1}.")

                if num_bonds < 0:
                    raise LoadFileError(f"Invalid number of bonds {num_atoms} defined in line {line_number + 1}.")

                num_read_at_cards = 0
                atom_atomic_num = []
                atom_coord_x = []
                atom_coord_y = []
                atom_coord_z = []
                state = MDLMolV2000ParserState.ATOM
            elif state == MDLMolV2000ParserState.ATOM:
                line_items = line.strip().split()

                try:
                    coord_x = float(line_items[0])
                    coord_y = float(line_items[1])
                    coord_z = float(line_items[2])
                except ValueError:
                    # Something is wrong with format
                    raise LoadFileError(f"Invalid atom coordinate value(s) at line {line_number + 1}.")

                try:
                    # Convert here atomic symbol to atomic number
                    if line_items[3] == "X":
                        atomic_num = -1
                    elif line_items[3] == "Q":
                        atomic_num = -2
                    else:
                        atomic_num = elements.symbol(line_items[3]).number
                except ValueError:
                    raise LoadFileError(f"Invalid atom symbol at line {line_number + 1}.")

                num_read_at_cards += 1
                atom_atomic_num.append(atomic_num)
                atom_coord_x.append(coord_x)
                atom_coord_y.append(coord_y)
                atom_coord_z.append(coord_z)

                if num_read_at_cards == num_atoms:
                    if not title:
                        title = path.name

                    at_coord_item = Item(
                        name=title,
                        data=AtomicCoordinates(
                            atomic_num=atom_atomic_num, 
                            x=atom_coord_x, 
                            y=atom_coord_y, 
                            z=atom_coord_z,
                        ),
                    )
                    result.items.append(at_coord_item)

                    state = MDLMolV2000ParserState.BOND
            elif state == MDLMolV2000ParserState.BOND:
                # TODO: read here explicit bonds, but the viewer must be reimplemented,
                # so that the bonds are not necessarily autogenerated.
                break

    if result.items:
        result.items[-1].metadata[babushka_priehala] = True

    return result
